### ISSUE TITLE
Use DOT syntax for field generation

### ISSUE THREAD

**Issue by gergelyszaz** [gergelyszaz/board-game-language#47]
**Is your feature request related to a problem? Please describe.**
It would be great to use a well known graph description language to define the board layout.

**Describe the solution you'd like**
I'd like to use DOT syntax.

**Describe alternatives you've considered**
Alternative: using a simple language.

**Additional context**
Sample result:

```yaml
name: sample game
board: |
  a -> b -> c
  a [ attribute1=b ]
```

or

```yaml
board: nodegraph.dot
```

or 

```yaml
board: |
  digraph {
    a->b->c
  }
```
